### ISSUE TITLE
It doesn't generate any token

### ISSUE THREAD

**Issue by avataat** [Weberowsky/Discord-tokens-generator#3]
When I run the program and I enter the number of tokens, it doesn't generate anything.

**Comment by Weberowsky** [comment]
Have you installed all dependencies?

**Comment by avataat** [comment]
> Have you installed all dependencies?

Yes, the program starts correctly but when i type the number (I tryed  numbers between 1 and 30) and I press enter it says _Press ctrl a ctrl c for copy... etc_ and there aren't any tokens.

**Comment by Weberowsky** [comment]
Try to use that code:
[Click](https://paste.gg/p/anonymous/c475b243b01149a490b4f72be651ba17)

If still does not work tell me what operation system do you use

**Comment by Tropixi** [comment]
File "C:\Users\vyric\Downloads\Discord-Tok_Gn.py", line 39
    workingtoken = working + token
IndentationError: unexpected indent

**Comment by Tropixi** [comment]
Windows 10 20h2 intel

**Comment by Tropixi** [comment]
```
import random
import os
import sys
import pyfiglet
import requests
from pathlib import Path

chars = "-abcdefghijklmnopq_rstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ123456789"
ascii_banner = pyfiglet.figlet_format("Token  generator")
print(ascii_banner)
file_path = Path('tokens.txt') 


ilosc = input("How many tokens to generate: \n")
ilosc = int(ilosc)
os.system('cls')

print("Generating working tokens.....")
print("Please wait")

working = '[WORK] '
err = '[ERROR] '

for i in range(ilosc):
    token1 = ""
    token2 = ""

    for c in range(84):
        token1 += random.choice(chars)

    token2 = 'mfa.'

    token1 = str(token1)
    token2 = str(token2)



token = token1 + token2
workingtoken = working + token
print(workingtoken)  


print("\n")
sys.stdout.write("\033[1;31m")
print("Tokens generated, if you want to copy tokens press [CTRL A] + [CTRL C]")
print("If no tokens have been generated, please restart the application and increase the number of tokens to be generated")
print("Source code: https://github.com/Weberowsky/Discord-tokens-generator")
sys.stdout.write("\033[0;0m")
input("")
```

It appears you indented line 39

**Comment by Tropixi** [comment]
New issue it only generates 1 token when you type 1-9999 no matter what number you insert.

**Comment by Tropixi** [comment]
Generating working tokens.....
Please wait


Tokens generated, if you want to copy tokens press [CTRL A] + [CTRL C]
If no tokens have been generated, please restart the application and increase the number of tokens to be generated
Source code: https://github.com/Weberowsky/Discord-tokens-generator


For version 1.

**Comment by Tropixi** [comment]
> Try to use that code:
> [Click](https://paste.gg/p/anonymous/c475b243b01149a490b4f72be651ba17)
> 
> If still does not work tell me what operation system do you use

```
Generating working tokens.....
Please wait
[WORK] lOCS1187IoOCzdPacdbT3Kd_MeEo1uGAL2BJMTFXbA__J36fLfAPm7uuKTNS_QBjxB_XQlEnlAPa6QNOuPGEmfa.


Tokens generated, if you want to copy tokens press [CTRL A] + [CTRL C]
If no tokens have been generated, please restart the application and increase the number of tokens to be generated
Source code: https://github.com/Weberowsky/Discord-tokens-generator
```
And for the second version, you provided it showed this.
the mfa. is in the wrong position as well and only 1/9999 tokens is generated?

**Comment by kgsensei** [comment]
> New issue it only generates 1 token when you type 1-9999 no matter what number you insert.

The reason for this is the weird indent thingy going on here:
```
     token2 = str(token2)

token = token1 + token2
workingtoken = working + token
print(workingtoken)  

print("\n")
```
It needs to be more like this:
```
     token2 = str(token2)
     token = token1 + token2
     workingtoken = working + token
     print(workingtoken)  

print("\n")
```
That way if the token works it prints for each working token not only one after the loop finishes.
It also might be good to update all the code. That will probably work best. For the raw code click [here](https://raw.githubusercontent.com/Weberowsky/Discord-tokens-generator/master/Discord-token-generator.py).


That should solve most of the issues. If you still have some please provide more information on the error.

**Comment by Tropixi** [comment]
Why do the tokens generated have this problem where mfa. is at the end
[WORK] __EzBr3k_rDsWHN71Ck4SgmFao7e_VpNH7kjkdlSlKosJwPVYjtPz6zOeRixX_2yOA8H4ncUVBA28kP5jqGemfa.

**Comment by Tropixi** [comment]
Figured it out you flipped line 39     token = token2 + token1
